/**
 * Journey game — interactive communication-practice scenarios.
 * Each scenario has Easy/Medium/Hard modes; each mode is a graph of "beats"
 * (conversations) with four choices that branch (poor answers route to a repair
 * beat) and end at a final reflection. Content is generated by
 * scripts/parse-journey.mjs from the founder's markdown.
 */
export type JourneyArea =
  | 'friends'
  | 'talking'
  | 'teasing'
  | 'people'
  | 'boundaries'
  | 'bigFeelings';

export type JourneyMode = 'easy' | 'medium' | 'hard';

/** 5 best · 4 good · 3 partial-repair · 2 passive · 1 poor */
export type ChoiceStars = 1 | 2 | 3 | 4 | 5;

export interface JourneyChoice {
  letter: 'A' | 'B' | 'C' | 'D';
  text: string;            // the full sentence the child taps — never one word
  stars: ChoiceStars;
  xp: number;              // 25 / 15 / 8 / 3 (repair: 20 / 10)
  traits: string[];        // e.g. ["Kindness","Confidence"]
  coaching: string;        // the "why", shown after choosing
  skillLearned?: string;   // optional named micro-skill
  tip?: string;            // shown on passive choices
  next: string;            // id of the next beat, or a reflection id
}

export interface JourneyBeat {
  id: string;
  kind: 'conversation' | 'repair';
  round?: number;          // 1..5 for conversation beats
  title?: string;
  narration: string;
  speaker?: string;        // who is talking (the other character)
  line?: string;           // what they say (the prompt)
  choices: JourneyChoice[];
}

export interface JourneyModeData {
  label: string;           // e.g. "The Tire Swing"
  cast?: string;
  setting?: string;
  start: string;           // first beat id
  beats: Record<string, JourneyBeat>;
  reflectionId: string;    // id that ends the mode (e.g. "reflection")
  reflection: string;      // final reflection text
  saveLine?: string;       // the "save this line" takeaway
}

export interface JourneyScenario {
  id: string;              // "friends-01"
  category: JourneyArea;
  index: number;           // 1..20
  title: string;
  skill: string;
  whyItMatters: string;
  modes: Record<JourneyMode, JourneyModeData>;
}
