// AUTO-GENERATED by scripts/parse-journey.mjs — do not edit by hand.
import type { JourneyArea } from '../types/journey';

/** Scenario count per journey category (for journey-completion math). */
export const SCENARIO_TOTALS: Partial<Record<JourneyArea, number>> = {"boundaries":11,"friends":22,"people":10,"talking":14,"teasing":11};
